# the compiler
CC = g++

# compiler flags:
#  -g    debugging info
#  -Wall compiler warnings
CFLAGS = -g -Wall -o

all: HW2_LinkedLists HW2_Die

HW2_LinkedLists: HW2_LinkedLists.cpp
	g++ -o HW2_LinkedLists HW2_LinkedLists.cpp

HW2_Die: HW2_Die.cpp
	g++ -o HW2_Die HW2_Die.cpp