# the compiler
CC = g++4.8

# compiler flags:
#  -g    debugging info
#  -Wall compiler warnings
CFLAGS = -g -Wall -o

all: main

# This has to included all the .cpp .h (and .o) files
main: main.cpp
	g++ LinkedListTemplate.cpp WallPost.cpp Wall.cpp User.cpp UserList.cpp main.cpp -o main